add 2023-05-25 URTI progress report
greatscottgadgets/lab-notes pull request #3
Opened 2023-05-26 13:17 UTC by mossmann

phase one completion

2023-05-31 21:13 UTC, epenelope requested changes
Great start! I've commented in line with specific suggestions for refining edits.

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We plan to build URTI as a system comprised of two printed circuit board assemblies: a mainboard, and a user interface board. The mainboard will include the radio section and a USB interface and will
remove the comma after mainboard
also, it's not clear what the adjective tactile is describing in the last sentence. If the adjective tactile is meant to describe the controls, we should remove the comma after tactile.

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We plan to build URTI as a system comprised of two printed circuit board assemblies: a mainboard, and a user interface board. The mainboard will include the radio section and a USB interface and will
The second sentence is a little bit hard to follow. I suggest splitting it into two sentences:
"The mainboard will include the radio section and a USB interface. It will be capable of serving as..."

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We will use [MAX2831](https://www.analog.com/en/products/max2831.html) or [MAX2830](https://www.analog.com/en/products/max2830.html) to convert quadrature analog baseband signals to an Intermediate F
I think you could explain why we selected those two components for evaluation. Reading this, it sounds like you are saying MAX2837 was also a candidate for URTI. We know why it wasn't a candidate, but the audience of this report might not have that context.

And why did we choose to test them individually? Is it because they were dissimilar enough that we couldn't rely on our familiarity with MAX2837? 

Finally, it's not clear what the word 'individually' means in the last sentence. Does it mean we tested each of those two components separately from MAX2837?

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We used [MAX2223EVKIT](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/max2223evkit.html), an off-the-shelf evaluation board, to test [MAX2223](https:/
The sentence "MAX2223 is similar but lacks baseband filters" doesn't make sense to me in this paragraph. What is it similar to?

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We tested MAX2223 because it was the component initially installed on the evaluation board, but we plan to use MAX2120 because of its analog baseband filter and low cost.
This seems out of place; I think this information belongs in line 87, where you first mention the component we chose.

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Both components worked as expected. We observed that they are capable of tuning well outside their advertised ranges. MAX2223 operated from 513 MHz to 2653 MHz while MAX2120 operated from 499 MHz to
The statement "both components worked as expected" seems to conflict with a statement in the following paragraph, "there are several other errors and omissions in the data sheet". If they worked as expected, what did we base our expectations on if not the datasheet?

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Because of our need to design many small PCBs for testing RF components and sub-circuits throughout the project, it was important to establish a baseline test PCB design featuring RF traces with 50 o
Replace the first sentence with: "Establishing a baseline test PCB design featuring RF traces with 50 ohm characteristic impedance and low-loss RF connectors at a reasonable cost was important because we will need to design many small PCBs for testing RF components and sub-circuits throughout the project."

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Because of our need to design many small PCBs for testing RF components and sub-circuits throughout the project, it was important to establish a baseline test PCB design featuring RF traces with 50 o
Replace "arrive upon a solution" with "arrive at a solution"

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +We plan to generate a single 40 MHz clock signal that is used as the ADC/DAC sample clock and also as a reference clock for each of the RF synthesizers. The mixers (RFFC5072) and quadrature transmitt
Change the first sentence to "We plan to generate a single 40 MHz clock signal that is used as the ADC/DAC sample clock and as a reference clock for each RF synthesizer. "

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +In the initial mainboard prototype we plan to use a single 40 MHz temperature-compensated crystal oscillator (TCXO). In the final mainboard design we will likely use a voltage-controlled crystal osci
Change the first sentence to: "We plan to use a single 40 MHz temperature-compensated crystal oscillator (TCXO) in the initial mainboard prototype."

Add a comma after the word 'design' in the second sentence

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Modern RF ICs of the sort we expect to use in URTI and related designs such as [Amalthea](https://github.com/greatscottgadgets/amalthea-hardware) often specify a maximum input power of 10 dBm to 20 d
Change 'affect' to 'effect'

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Modern RF ICs of the sort we expect to use in URTI and related designs such as [Amalthea](https://github.com/greatscottgadgets/amalthea-hardware) often specify a maximum input power of 10 dBm to 20 d
Change "The very wide operating frequency range and low cost requirements of URTI make this problem even more difficult to solve." to "URTI's wide operating frequency range and low-cost requirements make this problem even more challenging to solve."

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Another trick used by Lim is the use of the parasitic capacitance and inductance of the limiter diodes as elements in a low-pass filter (which can have a high cutoff frequency when using small diodes
Change "used by Lim is the use of" to "Lim uses is applying"

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Another trick used by Lim is the use of the parasitic capacitance and inductance of the limiter diodes as elements in a low-pass filter (which can have a high cutoff frequency when using small diodes
To clarify the antecedent, add a word: "This _technique_ improves the impedance match in the passband..."

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +During phase one we additionally made progress on phases four and eight. Although completion of the later phases is still a long way off, work toward those software development goals in parallel with
Add a comma after 'phase one'

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +During phase one we additionally made progress on phases four and eight. Although completion of the later phases is still a long way off, work toward those software development goals in parallel with
Change 'work' to 'working'

2023-05-31 21:13 UTC, epenelope commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Separate from URTI but partly in an effort to provide a platform for URTI developers, we have designed and assembled [Amalthea](https://github.com/greatscottgadgets/amalthea-hardware), a Software-Def
Replace 'in an effort to' with just 'to'

2023-05-31 21:13 UTC, epenelope requested changes
Great start! I've commented in line with specific suggestions for refining edits.

2023-06-02 16:31 UTC, mossmann commented on project-reports/2023-05-25-urti-progress-report/README.md
> +Another trick used by Lim is the use of the parasitic capacitance and inductance of the limiter diodes as elements in a low-pass filter (which can have a high cutoff frequency when using small diodes
I'm replacing "Another trick used by Lim is the use of" with "Lim also suggests using".

2023-06-02 16:56 UTC, mossmann commented
Thank you for the great edits! I've addressed all your suggestions, added a short section on DPDT RF switch testing, and updated the report date.

2023-06-08 16:00 UTC, epenelope approved these changes
This looks great; thanks, @mossmann !

2023-06-08 17:30 UTC, merged