Add 2024-06-21 URTI progress report
greatscottgadgets/lab-notes pull request #6
Opened 2024-06-21 17:08 UTC by mossmann

2024-07-02 19:08 UTC, epenelope requested changes
Great start, and sorry for taking so long to get to this review! I have some suggestions for improving clarity and adding more details in the comments.

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +Recently we have questioned the particular boundary between the mainboard and the user interface board. Although our overall architecture remains unchanged, we now consider the boundary to be an arbi
Suggest changing the first phrase to: "Recently, we have been reconsidering" since it's an ongoing process with a definite solution yet to be reached.
I think it would be helpful here to briefly explain what it was in this phase that prompted us to reconsider the boundary between the mainboard and the user interface board. Also, it's unclear to me what you mean by "overall architecture remains unchanged" and how the boundary between the user interface board can change but not affect the overall architecture. Can you say specifically what will remain unchanged?

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +Recently we have questioned the particular boundary between the mainboard and the user interface board. Although our overall architecture remains unchanged, we now consider the boundary to be an arbi
How about "flexible design element" instead of "arbitrary choice"?

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +Recently we have questioned the particular boundary between the mainboard and the user interface board. Although our overall architecture remains unchanged, we now consider the boundary to be an arbi
Suggest replacing "It may be possible and desirable to implement the handheld platform with a single printed circuit board. Alternatively we may prefer a two-board solution with a different boundary than we originally anticipated" with "This means that we might opt for a single printed circuit board for the handheld platform, or we might stick with a two-board solution with a different boundary than originally planned. "

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +For now we are focused on designing the handheld platform, and we are willing to adjust the two-board plan however necessary to best achieve our vision for a handheld test instrument. Once an initial
Add a comma after "for now"

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +For now we are focused on designing the handheld platform, and we are willing to adjust the two-board plan however necessary to best achieve our vision for a handheld test instrument. Once an initial
When you say "Once an initial design of the handheld platform is completed, we will reassess our plan to produce a USB peripheral platform." it kind of sounds like not maintaining a peripheral platform independent of the user interface at all is one of the options on the table.
Maybe remove that sentence and replace "While we originally intended the USB peripheral platform and the handheld platform to share a mainboard design, we may instead choose to maintain a separate design for the USB peripheral platform" with "Once we have an initial design for the mainboard platform, we will weigh the potential benefits of maintaining a separate design for the USB peripheral platform" to make it clear that this separation of the two designs is a decision dependent on how things progress with the user interface board design.

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +In preparation for the initial user interface board design we selected several key components. When going through this process for the RF components of the mainboard, we felt that it was important to
Folks reading this may wonder why we felt comfortable not doing hands-on testing in this phase as we did in the previous one.

2024-07-02 19:08 UTC, epenelope commented on project-reports/2024-06-21-urti-progress-report/README.md
> +We made further progress on phases four and five, creating mainboard firmware, gateware, and host software sufficient to fully validate the mainboard prototype design. A few small mainboard design er
Is the work on four and five published yet, or is it still a local WIP? Are there issues we can link to for the mainboard design errors the team uncovered?

2024-08-01 17:37 UTC, mossmann commented on project-reports/2024-06-21-urti-progress-report/README.md
> +Recently we have questioned the particular boundary between the mainboard and the user interface board. Although our overall architecture remains unchanged, we now consider the boundary to be an arbi
include block diagram from https://github.com/greatscottgadgets/lab-notes/tree/main/project-reports/2023-06-02-urti-progress-report for clarification

2024-08-01 17:47 UTC, mossmann commented on project-reports/2024-06-21-urti-progress-report/README.md
> +In preparation for the initial user interface board design we selected several key components. When going through this process for the RF components of the mainboard, we felt that it was important to
Clarify that the reason we tested components for the mainboard was that we needed to measure performance in applications not described by their data sheets. For the user interface board, all components will be used in a manner consistent with their data sheets.

2024-08-01 17:52 UTC, mossmann commented on project-reports/2024-06-21-urti-progress-report/README.md
> +We made further progress on phases four and five, creating mainboard firmware, gateware, and host software sufficient to fully validate the mainboard prototype design. A few small mainboard design er
I'll link to the mainboard issues. Phase four and five work is in @mndza's repos. We will migrate those things to the greatscottgadgets organization and provide links later.

2024-08-02 17:48 UTC, mossmann commented on project-reports/2024-06-21-urti-progress-report/README.md
> +Recently we have questioned the particular boundary between the mainboard and the user interface board. Although our overall architecture remains unchanged, we now consider the boundary to be an arbi
Actually the block diagram was already included.

2024-08-05 21:17 UTC, epenelope approved these changes
Looks great!

2024-08-05 22:48 UTC, merged